# Generated by Django 3.0.3 on 2020-04-26 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'هه\u200cژمار',
            },
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='وێنه\u200c')),
                ('nameEg', models.CharField(max_length=100, verbose_name='ناوی بیانی')),
                ('nameKu', models.CharField(max_length=100, verbose_name='ناوی كوردی')),
                ('detiles', models.CharField(max_length=100, verbose_name='ورده\u200cكاری')),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='ریكه\u200cوتی دانان')),
            ],
            options={
                'verbose_name_plural': 'جۆره\u200cكانی خواردن',
            },
        ),
        migrations.CreateModel(
            name='Dliver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=110)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'شۆفێر',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('price', models.CharField(max_length=11)),
                ('disprice', models.CharField(max_length=11)),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=300)),
                ('detiles', models.CharField(max_length=300)),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='date added')),
                ('is_dispriced', models.BooleanField(default=False)),
                ('cost', models.CharField(blank=True, max_length=11, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Food_category', to='deliver.Cat')),
            ],
            options={
                'verbose_name_plural': 'خواردنه\u200cكان',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=110)),
                ('phone', models.CharField(max_length=110)),
                ('address', models.CharField(max_length=110)),
                ('total_price', models.CharField(max_length=11)),
                ('phoneid', models.CharField(default='Unknown', max_length=110)),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='date added')),
                ('last_edit', models.DateTimeField(auto_now=True, verbose_name='last edit')),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'داواكاریه\u200cكان',
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
                ('status', models.BooleanField(default=False)),
                ('dliver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliver.Dliver')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliver.Request')),
            ],
            options={
                'verbose_name_plural': 'باركراو',
            },
        ),
        migrations.CreateModel(
            name='Specify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='date added')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specify_food', to='deliver.Food')),
            ],
            options={
                'verbose_name_plural': 'تام و چێش',
            },
        ),
        migrations.CreateModel(
            name='RequestDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=11)),
                ('total_price', models.CharField(max_length=11)),
                ('phoneid', models.CharField(default='Unknown', max_length=110)),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='date added')),
                ('last_edit', models.DateTimeField(auto_now=True, verbose_name='last edit')),
                ('status', models.BooleanField(default=False)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_food', to='deliver.Food')),
                ('specify', models.ManyToManyField(to='deliver.Specify')),
            ],
            options={
                'verbose_name_plural': 'ورده\u200cكاری داواكاری',
            },
        ),
        migrations.AddField(
            model_name='request',
            name='request_detail',
            field=models.ManyToManyField(to='deliver.RequestDetail'),
        ),
    ]
