# Generated by Django 3.0.3 on 2020-05-31 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motors',
            name='date_added',
        ),
    ]
