# Generated by Django 3.0.3 on 2020-05-21 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliver', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dipricing',
            options={'verbose_name_plural': 'disprice'},
        ),
    ]
