# Generated by Django 3.0.3 on 2020-05-16 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='date_added',
            field=models.DateField(auto_now_add=True, verbose_name='به\u200cره\u200cواری دانان'),
        ),
        migrations.AlterField(
            model_name='food',
            name='detiles',
            field=models.CharField(max_length=300, verbose_name='ورده\u200cكاری'),
        ),
        migrations.AlterField(
            model_name='food',
            name='disprice',
            field=models.CharField(max_length=11, verbose_name='داشكاند'),
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='وێنه\u200c'),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.CharField(max_length=11, verbose_name='نرخ'),
        ),
        migrations.AlterField(
            model_name='food',
            name='subtitle',
            field=models.CharField(max_length=300, verbose_name='ناونیشان'),
        ),
        migrations.AlterField(
            model_name='food',
            name='title',
            field=models.CharField(max_length=50, verbose_name='ناو'),
        ),
    ]
