# Generated by Django 3.0.3 on 2020-05-21 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliver', '0002_auto_20200521_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specify',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifies', to='deliver.Food'),
        ),
    ]
