# Generated by Django 3.0.3 on 2020-05-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliver', '0002_auto_20200516_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='detiles',
        ),
        migrations.AddField(
            model_name='cat',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
