# Generated by Django 3.0.3 on 2020-06-11 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliver', '0004_auto_20200611_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='relcustomer', to='deliver.Customer'),
        ),
    ]
