# Generated by Django 3.0.3 on 2020-06-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliver', '0005_request_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='وێنه\u200c'),
        ),
    ]
