# Generated by Django 3.0.3 on 2020-06-15 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliver', '0007_customer_phoneid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='phoneid',
        ),
        migrations.RemoveField(
            model_name='requestdetail',
            name='phoneid',
        ),
        migrations.AddField(
            model_name='requestdetail',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customerRequestD', to='deliver.Customer'),
        ),
    ]
