# Generated by Django 3.0.3 on 2020-06-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliver', '0008_auto_20200615_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='dashkandin',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='requestdetail',
            name='dashkandin',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
