# Generated by Django 3.0.3 on 2020-06-19 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliver', '0010_auto_20200618_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='user',
            new_name='customer',
        ),
    ]
