# Generated by Django 3.0.3 on 2020-06-21 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliver', '0011_auto_20200619_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(verbose_name='add date')),
                ('status', models.BooleanField(default=False)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliver.Dliver')),
            ],
            options={
                'verbose_name_plural': 'بنکە',
            },
        ),
    ]
