# Generated by Django 3.0.3 on 2020-06-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliver', '0012_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='title',
            field=models.CharField(max_length=110),
        ),
    ]
