# Generated by Django 3.0.3 on 2020-06-22 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliver', '0013_auto_20200622_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='add_date',
            field=models.DateTimeField(auto_now=True, verbose_name='add date'),
        ),
        migrations.CreateModel(
            name='BnkaUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='date added')),
                ('bnka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BnkaUser', to='deliver.Warehouse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'بنکەو بەکارهێنەر',
            },
        ),
    ]
