# Generated by Django 3.0.3 on 2020-06-25 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliver', '0015_auto_20200622_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='war',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Cat_warehouse', to='deliver.Warehouse'),
        ),
    ]
