# Generated by Django 3.0.3 on 2020-06-26 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliver', '0016_cat_war'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Food_warehouse', to='deliver.Warehouse'),
        ),
    ]
