# Generated by Django 3.0.3 on 2020-06-27 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliver', '0017_food_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='warehouse',
        ),
    ]
